# Generated by Django 4.0 on 2023-05-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='debt',
        ),
    ]
