# Generated by Django 4.0 on 2023-05-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
