# Generated by Django 4.0 on 2023-05-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_debt'),
        ('book', '0003_remove_bookinstance_imprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='date_borrow',
            field=models.DateField(auto_now_add=True, default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
