# Generated by Django 4.0 on 2023-05-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_borrower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower',
        ),
    ]
